export const CUSTOMER_LOGOS = [
  { name: "Aldar", src: "/logos/clients/aldar.png" },
  { name: "BTG Pactual", src: "/logos/clients/btg-pactual.png" },
  { name: "IHC", src: "/logos/clients/ihc.png" },
  { name: "FAB", src: "/logos/clients/fab.svg" },
  { name: "UAE Presidential Court", src: "/logos/clients/uae-presidential-court.png" },
  { name: "ADCS", src: "/logos/clients/adcsc.png" },
  { name: "e&", src: "/logos/clients/eand.svg" },
  { name: "ADIA", src: "/logos/clients/adia.svg" },
  { name: "DCT", src: "/logos/clients/dct.png" },
  { name: "DMT", src: "/logos/clients/dmt.svg" },
  { name: "Emaar", src: "/logos/clients/emaar.svg" },
  { name: "IFZA", src: "/logos/clients/ifza.png" },
  { name: "Masdar", src: "/logos/clients/masdar.svg" },
  { name: "Miral", src: "/logos/clients/miral.png" },
  { name: "Multiply Group", src: "/logos/clients/multiply-group.svg" },
  { name: "RAKEZ", src: "/logos/clients/rakez.svg" },
  { name: "ADNEC", src: "/logos/clients/adnec.png" },
  { name: "ADX", src: "/logos/clients/adx.png" },
  { name: "MOFAIC", src: "/logos/clients/mofaic.png" },
  { name: "ADAA", src: "/logos/clients/adaa.svg" },
  { name: "Crypto.com", src: "/logos/clients/crypto-com.svg" },
  { name: "Adani", src: "/logos/clients/adani.svg" },
  { name: "Oncoclínicas", src: "/logos/clients/oncoclnicas.png" },
  { name: "Grupo Nutresa", src: "/logos/clients/grupo-nutresa.svg" },
] as const;
